name: Brew

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # `brew install` pulls taps from GH, don't need to checkout the repo
      - name: Install sgr
        run: brew install splitgraph/splitgraph/sgr

      - name: Test sgr install (brew test sgr)
        run: brew test sgr
